# Spring 설정
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/JGITKINS?allowMultiQueries=true
      username: root
      password: root1234
      pool-name: CP
      maximum-pool-size: 5
      connection-timeout: 8000
      max-lifetime: 147000